config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        flash[:success] = "Todo was successfully created."
        format.html { redirect_to @todo }
        format.json { render :show, status: :created, location: @todo }
      else
        flash[:alert] = 'There was a problem creating the Todo.'
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        flash[:success] = "Todo was successfully updated."
        format.html { redirect_to @todo }
        format.json { render :show, status: :ok, location: @todo }
      else
        flash[:alert] = 'There was a problem updating the Todo.'
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      flash[:success] = "Todo was successfully destroyed."
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Todo with Foundation</a></h1>
    </li>

    <li class="toggle-topbar">
      <a href="#"><span>Menu</span></a>
    </li>
  </ul>

    <section class="top-bar-section">
      <ul class="right">
        <li class="has-dropdown no-click">
          <a href="#">Menu</a>
          <ul class="dropdown">
            <li><a href="#">Login</a></li>
            <li><%= link_to "Create a todo", new_todo_path %></li>
          </ul>
        </li>
      </ul>
    </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>

    <div class="row">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <%= content_tag :div, msg, class: "alert-box #{name} radius" %>
        <% end %>
      <% end %>
    </div>

    <div class="row">
      <div class="small-3 column">
        <h3>Todo with Foundation</h3>
      </div>
      <div class="small-9 column">
        <%= yield %>
      </div>
    </div>


    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :title, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_field :title %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :notes, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_area :notes %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-10 small-offset-2 columns">
          <%= f.submit %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<dl class="tabs" data-tab data-options="deep_linking: true">
  <dd class="active">
    <%= link_to 'View list', todos_path %>
  </dd>
  <dd>
    <%= link_to 'New todo', new_todo_path %>
  </dd>
</dl>



<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td>
          <span data-tooltip aria-haspopup="true" class="has-tip tip-left" title="<%= "Created on #{todo.created_at.strftime("%m%e%Y at %w:%M %p")}, Last modified on #{todo.updated_at.strftime("%m%e%Y at %w:%M %p")}" %>">
            <%= todo.title %>
          </span>
        </td>
        <td>

          <% if todo.notes? %>
            <a href="#" data-reveal-id="todo-<%= todo.id %>-notes">View notes</a>

            <div id="todo-<%= todo.id %>-notes" class="reveal-modal" data-reveal>
              <%= todo.notes %>
              <a class="close-reveal-modal">&#215;</a>
            </div>
          <% end %>

        </td>
        <td><%= link_to 'Show', todo, class: 'button tiny radius' %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo), class: 'button tiny radius' %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny radius' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path, class: 'button success radius small' %>

app/views/todos/new.html.erb
<!--  app/views/todos/new.html.erb -->

<dl class="tabs" data-tab data-options="deep_linking:true">
  <dd>
    <%= link_to 'View list', todos_path %>
  </dd>
  <dd class="active">
    <%= link_to 'New todo', new_todo_path %>
  </dd>
</dl>

<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @todo.notes %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>